name = "blue-turtle-squad"
main = "index.js"
compatibility_date = "2026-08-26"

[[d1_databases]]
binding = "DB"
database_name = "blue-turtle-squad"
database_id = "72c5d7db-a094-479a-b8d9-3c7b8e8e9003"

[[d1_databases]]
binding = "DB_WISATA"
database_name = "wisata-bahari"
database_id = "982c0f85-0558-42ee-9dc9-d5e2cdc9c914"
